In [1]:
import numpy as np
import pandas as pd

# Exercise 1: Create array and reshape to 2x5 matrix
arr1 = np.arange(1, 11).reshape(2, 5)
print("Exercise 1:\n", arr1)

# Exercise 2: Extract elements between 5th and 15th index (inclusive of 5, exclusive of 15)
arr2 = np.arange(1, 21)
subset = arr2[5:15]
print("\nExercise 2:\n", subset)

# Exercise 3: Create series and add new item
fruits = pd.Series({'apples': 3, 'bananas': 2, 'oranges': 1})
fruits['pears'] = 4
print("\nExercise 3:\n", fruits)

# Exercise 4: Create dataframe with 10 rows
data = {
    'name': ['Alice', 'Bob', 'Charlie', 'David', 'Eve', 'Frank', 'Grace', 'Hannah', 'Ian', 'Jane'],
    'age': [25, 32, 28, 45, 30, 29, 35, 22, 40, 27],
    'gender': ['F', 'M', 'M', 'M', 'F', 'M', 'F', 'F', 'M', 'F']
}
df = pd.DataFrame(data)
print("\nExercise 4:\n", df)

# Exercise 5: Add new column 'occupation'
df['occupation'] = ['Programmer', 'Manager', 'Analyst', 'Programmer', 'Manager', 
                    'Analyst', 'Programmer', 'Manager', 'Analyst', 'Programmer']
print("\nExercise 5:\n", df)

# Exercise 6: Select rows where age >= 30
age_filter = df[df['age'] >= 30]
print("\nExercise 6:\n", age_filter)

# Exercise 7: Save to CSV, read it back, and display
df.to_csv('people.csv', index=False)
df_from_csv = pd.read_csv('people.csv')
print("\nExercise 7:\n", df_from_csv)


Exercise 1:
 [[ 1  2  3  4  5]
 [ 6  7  8  9 10]]

Exercise 2:
 [ 6  7  8  9 10 11 12 13 14 15]

Exercise 3:
 apples     3
bananas    2
oranges    1
pears      4
dtype: int64

Exercise 4:
       name  age gender
0    Alice   25      F
1      Bob   32      M
2  Charlie   28      M
3    David   45      M
4      Eve   30      F
5    Frank   29      M
6    Grace   35      F
7   Hannah   22      F
8      Ian   40      M
9     Jane   27      F

Exercise 5:
       name  age gender  occupation
0    Alice   25      F  Programmer
1      Bob   32      M     Manager
2  Charlie   28      M     Analyst
3    David   45      M  Programmer
4      Eve   30      F     Manager
5    Frank   29      M     Analyst
6    Grace   35      F  Programmer
7   Hannah   22      F     Manager
8      Ian   40      M     Analyst
9     Jane   27      F  Programmer

Exercise 6:
     name  age gender  occupation
1    Bob   32      M     Manager
3  David   45      M  Programmer
4    Eve   30      F     Manager
6  Grace   35